import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import Footer from "@/components/Footer/Footer";
import styles from "../content.module.scss";

export const metadata: Metadata = { title: "Услуги: шкалы, пересвет и ремонт приборных панелей", description: "Изготовление шкал приборов по индивидуальному дизайну, пересвет, ремонт и элементы приборных панелей в Краснодаре. Заказы по всей России.", alternates: { canonical: "/services" } };
const items = [
  { id: "custom", title: "Шкалы приборов на заказ", price: "от 7 000 ₽", text: "Создаём накладку под конкретную модель и задачу: от аккуратного OEM+ до полностью авторского дизайна.", list: ["новая графика, шкалы и шрифты", "нанесение логотипов и индивидуальных обозначений", "изменение цвета и характера подсветки", "согласование макета до изготовления"] },
  { id: "lighting", title: "Пересвет приборной панели", price: "от 3 500 ₽", text: "Обновляем штатную подсветку, добиваемся равномерного свечения и подбираем оттенок, который не утомляет глаза.", list: ["замена цвета и яркости", "устранение тёмных и пересвеченных зон", "сочетание со шкалой и интерьером", "финальная проверка после сборки"] },
  { id: "repair", title: "Ремонт приборных панелей", price: "от 2 500 ₽", text: "Диагностируем неисправность и восстанавливаем панель, когда пропадает индикация, мерцает подсветка или повреждены элементы.", list: ["диагностика перед работой", "ремонт электроники и контактов", "восстановление индикации", "проверка работоспособности"] },
  { id: "elements", title: "Стрелки, кольца и платы", price: "по расчёту", text: "Изготавливаем отдельные элементы приборки — как самостоятельную работу или часть комплексного проекта.", list: ["стрелки и декоративные кольца", "платы и элементы подсветки", "замена повреждённых деталей", "индивидуальный подбор под панель"] },
];
export default function ServicesPage() { const schema = { "@context": "https://schema.org", "@type": "ItemList", name: "Услуги Carmanof", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, item: { "@type": "Service", name: item.title, description: item.text, provider: { "@type": "AutomotiveBusiness", name: "Carmanof" }, areaServed: "Россия", url: `https://carmanof.ru/services#${item.id}` } })) }; return <div className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><header className={styles.hero}><p className={styles.eyebrow}>Услуги Carmanof</p><h1>Работаем с приборкой <span>целиком</span></h1><p>От идеи новой шкалы до ремонта, пересвета и проверки собранной панели. Берёмся за нестандартные задачи и заранее объясняем, какой результат реалистичен.</p></header><main className={styles.body}>{items.map((item, index) => <section className={styles.row} id={item.id} key={item.id}><span>0{index + 1}</span><h2>{item.title}</h2><div><p>{item.text}</p><ul>{item.list.map((point) => <li key={point}>{point}</li>)}</ul></div><strong>{item.price}</strong></section>)}<Link className={styles.cta} href="/#contact">Рассчитать вашу задачу <ArrowUpRight /></Link></main><Footer /></div>; }
